INSERT INTO
shippers(
  name,
  email,
  password,
  phone_number,
  image_url,
  number_of_deliveries,
  shipper_rating_sum,
  bio,
  company_information,
  fleet,
  driving_record,
  total_declined
)
VALUES
  (
    'John Doe',
    'johndoe@example.com',
    'test',
    '4165551847',
    'https://www.jdl.co.uk/wp-content/uploads/2016/10/avatar-m.png',
    10,
    5,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Toyota Corolla',
    'porttitor leo a diam sollicitudin',
    0
  ),
  (
    'Jane Foster',
    'jane@example.com',
    'test',
    '4165551111',
    'https://socoshaping.com/wp-content/uploads/2019/02/unknown-woman.png',
    20,
    5,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Volkswagon Jetta',
    'porttitor leo a diam sollicitudin',
    0
  ),
  (
    'Alex Fisher',
    'alexfisher@example.com',
    'test',
    '4161232222',
    'https://www.jdl.co.uk/wp-content/uploads/2016/10/avatar-m.png',
    30,
    4,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Honda CRV',
    'porttitor leo a diam sollicitudin',
    1
  ),
  (
    'David',
    'david@example.com',
    'test',
    '4162223333',
    'https://www.jdl.co.uk/wp-content/uploads/2016/10/avatar-m.png',
    20,
    4,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Ford F150',
    'porttitor leo a diam sollicitudin',
    3
  ),
  (
    'Blake',
    'blake@example.com',
    'test',
    '6473332354',
    'https://www.jdl.co.uk/wp-content/uploads/2016/10/avatar-m.png',
    27,
    5,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Toyota Rav4',
    'porttitor leo a diam sollicitudin',
    0
  ),
  (
    'Alison',
    'alison@example.com',
    'test',
    '6472223333',
    'https://socoshaping.com/wp-content/uploads/2019/02/unknown-woman.png',
    57,
    5,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Toyota Corolla',
    'porttitor leo a diam sollicitudin',
    0
  ),
  (
    'Brandon McDonald',
    'brandom@example.com',
    'test',
    '4165551847',
    'https://www.jdl.co.uk/wp-content/uploads/2016/10/avatar-m.png',
    10,
    5,
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    'Company LLC',
    'Toyota Corolla',
    'porttitor leo a diam sollicitudin',
    0
  ),
  (
    'Madeline Mckee',
    'mus@outlook.couk',
    'test',
    '7825872234',
    'https://socoshaping.com/wp-content/uploads/2019/02/unknown-woman.png',
    33,
    4,
    'tempor erat neque non quam. Pellentesque',
    'Luctus Ut Pellentesque Institute',
    'Honda Civic',
    'lobortis mauris. Suspendisse aliquet molestie',
    2
  ),
  (
    'Brianna Reed',
    'felis.nulla.tempor@google.net',
    'test',
    '3363145922',
    'https://socoshaping.com/wp-content/uploads/2019/02/unknown-woman.png',
    57,
    5,
    'Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies',
    'Ante Maecenas Incorporated',
    'Volkswagen Tiguan',
    'sit amet ultricies sem magna',
    1
  );